const express = require("express");
const bodyParser = require('body-parser');
var cors = require('cors')
var nodemailer = require('nodemailer');

const app = express()

app.use(cors());



var transport = nodemailer.createTransport({
    host: "mail.alumnustest.forge.org.in",
    port: 587,
    auth: {
        user: "mailmodule@alumnustest.forge.org.in", //generated by Mailtrap
        pass: "mailmodule" //generated by Mailtrap
    }
});

var mailOptions = {
    from: '"forge mail" <mailmodule@alumnustest.forge.org.in>',
    to: 'johnswaroop28@gmail.com, johndon65@gmail.com',
    subject: 'Nice Nodemailer test',
    text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
    html: '<b>Hey there! </b><br> This is our first message sent with Nodemailer'
};


app.get('/', (req, res) => {

    
    console.log('get request');

    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
    });

    res.send("working");

});

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: true
}));

app.post('/', (req, res) => {

    console.log('post request');

    console.log(req.body.data);

    var arr = req.body.data;

    res.send(arr);

})

app.listen(8080, () => {
    console.log('server running');
});